# Generated by Django 4.1.7 on 2024-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('roles', models.CharField(choices=[('admin', 'admin'), ('SuperAdmin', 'SuperAdmin'), ('User', 'User')], max_length=20)),
            ],
        ),
    ]
